version: 0.2
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-super-bean-service-role
  ComputeType:  BUILD_GENERAL1_SMALL
  #Image: image
  #Timeout: minutes
  
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python3.8 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy